### ISSUE TITLE
???

### ISSUE THREAD

**Issue by wenka** [seothemes/markdown#2]
Fatal error: Uncaught Error: Class 'Easy_Markdown' not found in /var/www/wordpress/wp-content/plugins/markdown-editor/includes/class-markdown-editor.php:113 Stack trace: #0 /var/www/wordpress/wp-content/plugins/markdown-editor/includes/class-markdown-editor.php(48): Markdown_Editor->load_jetpack_markdown_module() #1 /var/www/wordpress/wp-content/plugins/markdown-editor/includes/class-markdown-editor.php(61): Markdown_Editor->__construct() #2 /var/www/wordpress/wp-content/plugins/markdown-editor/markdown-editor.php(38): Markdown_Editor::get_instance() #3 /var/www/wordpress/wp-admin/includes/plugin.php(1882): include('/var/www/wordpr...') #4 /var/www/wordpress/wp-admin/plugins.php(164): plugin_sandbox_scrape('markdown-editor...') #5 {main} thrown in /var/www/wordpress/wp-content/plugins/markdown-editor/includes/class-markdown-editor.php on line 113

**Comment by delfer** [comment]
Got the same on /plugins.php
WordPress 4.9.7 + JP-Markdown
